import {
  FaBuilding,
  FaUserTie,
  FaProjectDiagram,
  FaUserCog,
  FaUsersCog,
  FaShieldAlt,
  FaCubes,
  FaTasks,
  FaLock,
  FaUserShield,
  FaUsers,
} from "react-icons/fa";

export const securityChildren = [
  {
    to: "/admin/company",
    label: "Company",
    icon: <FaBuilding className="text-xl" />,
    description: "Manage company information and settings",
    category: "Organization",
    color: "from-blue-500 to-cyan-500",
  },
  {
    to: "/admin/employee",
    label: "Employee",
    icon: <FaUserTie className="text-xl" />,
    description: "Manage employee records and details",
    category: "Organization",
    color: "from-purple-500 to-pink-500",
  },
  {
    to: "/admin/software-group",
    label: "Software Group",
    icon: <FaProjectDiagram className="text-xl" />,
    description: "Configure software groups and permissions",
    category: "Access Control",
    color: "from-green-500 to-emerald-500",
  },
  {
    to: "/admin/users",
    label: "Users",
    icon: <FaUserCog className="text-xl" />,
    description: "Manage user accounts and access",
    category: "User Management",
    color: "from-orange-500 to-amber-500",
  },
  {
    to: "/admin/group-users",
    label: "Group Users",
    icon: <FaUsersCog className="text-xl" />,
    description: "Assign users to groups",
    category: "User Management",
    color: "from-red-500 to-rose-500",
  },
  {
    to: "/admin/security-log",
    label: "Security Log",
    icon: <FaShieldAlt className="text-xl" />,
    description: "View security logs and activities",
    category: "Monitoring",
    color: "from-indigo-500 to-blue-500",
  },
  {
    to: "/admin/modules",
    label: "Modules",
    icon: <FaCubes className="text-xl" />,
    description: "Manage system modules",
    category: "System",
    color: "from-teal-500 to-cyan-500",
  },
  {
    to: "/admin/modules-functionalities",
    label: "Modules Functionalities",
    icon: <FaTasks className="text-xl" />,
    description: "Configure module functionalities",
    category: "System",
    color: "from-violet-500 to-purple-500",
  },
  {
    to: "/admin/group-rights",
    label: "Group Rights",
    icon: <FaLock className="text-xl" />,
    description: "Set group permissions and rights",
    category: "Access Control",
    color: "from-amber-500 to-yellow-500",
  },
  {
    to: "/admin/user-module-access",
    label: "Users Module Access",
    icon: <FaUserShield className="text-xl" />,
    description: "Manage user module access",
    category: "Access Control",
    color: "from-rose-500 to-pink-500",
  },
  {
    to: "/admin/groups",
    label: "Group Management",
    icon: <FaUsers className="text-xl" />,
    description: "Create and manage user groups",
    category: "User Management",
    color: "from-sky-500 to-blue-500",
  },
];
